version: '3.8'
services:
    web:
        build:
            context: ./docker
            dockerfile: PHP.dockerfile
        container_name: php_server
        environment:
            XDEBUG_CONFIG: client_host=host.docker.internal
        volumes: 
            - .:/var/www/html
            - ./docker/my-conf.conf:/etc/apache2/sites-available/000-default.conf
        container_name: web
        expose: 
            - "9001"
        ports:
            - "80:80"
    mysql:
        image: mariadb:latest
        container_name: mysql_server
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'tutorial'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'tutorial'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - "3306:3306"
volumes:
    mysqldata: {}

